RTL_CODES = ["ar", "he", "ur", "fa"]

LANGUAGES = [
    {"code": "en", "name": "English", "native": "English", "flag": "🇬🇧"},
    {"code": "it", "name": "Italian", "native": "Italiano", "flag": "🇮🇹"},
    {"code": "hi", "name": "Hindi", "native": "हिन्दी", "flag": "🇮🇳"},
    {"code": "es", "name": "Spanish", "native": "Español", "flag": "🇪🇸"},
    {"code": "fr", "name": "French", "native": "Français", "flag": "🇫🇷"},
    {"code": "de", "name": "German", "native": "Deutsch", "flag": "🇩🇪"},
    {"code": "pt", "name": "Portuguese", "native": "Português", "flag": "🇵🇹"},
    {"code": "ar", "name": "Arabic", "native": "العربية", "flag": "🇸🇦"},
    {"code": "zh", "name": "Chinese", "native": "中文", "flag": "🇨🇳"},
    {"code": "ja", "name": "Japanese", "native": "日本語", "flag": "🇯🇵"},
    {"code": "ru", "name": "Russian", "native": "Русский", "flag": "🇷🇺"},
    {"code": "tr", "name": "Turkish", "native": "Türkçe", "flag": "🇹🇷"},
    {"code": "bn", "name": "Bengali", "native": "বাংলা", "flag": "🇧🇩"},
    {"code": "ur", "name": "Urdu", "native": "اردو", "flag": "🇵🇰"},
    {"code": "ko", "name": "Korean", "native": "한국어", "flag": "🇰🇷"},
    {"code": "nl", "name": "Dutch", "native": "Nederlands", "flag": "🇳🇱"},
    {"code": "pl", "name": "Polish", "native": "Polski", "flag": "🇵🇱"},
    {"code": "sv", "name": "Swedish", "native": "Svenska", "flag": "🇸🇪"},
    {"code": "id", "name": "Indonesian", "native": "Bahasa Indonesia", "flag": "🇮🇩"},
    {"code": "vi", "name": "Vietnamese", "native": "Tiếng Việt", "flag": "🇻🇳"},
    {"code": "th", "name": "Thai", "native": "ไทย", "flag": "🇹🇭"},
    {"code": "el", "name": "Greek", "native": "Ελληνικά", "flag": "🇬🇷"},
    {"code": "he", "name": "Hebrew", "native": "עברית", "flag": "🇮🇱"},
    {"code": "fa", "name": "Persian", "native": "فارسی", "flag": "🇮🇷"},
    {"code": "uk", "name": "Ukrainian", "native": "Українська", "flag": "🇺🇦"},
    {"code": "ro", "name": "Romanian", "native": "Română", "flag": "🇷🇴"},
    {"code": "cs", "name": "Czech", "native": "Čeština", "flag": "🇨🇿"},
    {"code": "hu", "name": "Hungarian", "native": "Magyar", "flag": "🇭🇺"},
    {"code": "fi", "name": "Finnish", "native": "Suomi", "flag": "🇫🇮"},
    {"code": "da", "name": "Danish", "native": "Dansk", "flag": "🇩🇰"},
    {"code": "no", "name": "Norwegian", "native": "Norsk", "flag": "🇳🇴"},
    {"code": "ta", "name": "Tamil", "native": "தமிழ்", "flag": "🇮🇳"},
    {"code": "te", "name": "Telugu", "native": "తెలుగు", "flag": "🇮🇳"},
    {"code": "mr", "name": "Marathi", "native": "मराठी", "flag": "🇮🇳"},
    {"code": "ms", "name": "Malay", "native": "Bahasa Melayu", "flag": "🇲🇾"},
    {"code": "tl", "name": "Filipino", "native": "Filipino", "flag": "🇵🇭"},
    {"code": "sw", "name": "Swahili", "native": "Kiswahili", "flag": "🇰🇪"},
    {"code": "bg", "name": "Bulgarian", "native": "Български", "flag": "🇧🇬"},
    {"code": "sr", "name": "Serbian", "native": "Српски", "flag": "🇷🇸"},
    {"code": "hr", "name": "Croatian", "native": "Hrvatski", "flag": "🇭🇷"},
    {"code": "sk", "name": "Slovak", "native": "Slovenčina", "flag": "🇸🇰"},
    {"code": "ca", "name": "Catalan", "native": "Català", "flag": "🇪🇸"},
]
